import { ROLES, type Role } from "./roles";
import { PERMISSIONS, type Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.ADMIN]: [PERMISSIONS.ADMIN_ALL],
  [ROLES.PENTESTER]: [
    PERMISSIONS.PENTEST_DASHBOARD_READ,
    PERMISSIONS.PENTEST_PROJECT_READ,
    PERMISSIONS.PENTEST_VULNERABILITY_READ,
    PERMISSIONS.PENTEST_VULNERABILITY_CREATE,
    PERMISSIONS.PENTEST_VULNERABILITY_UPDATE,
    PERMISSIONS.PENTEST_REPORT_EXPORT,
  ],
  [ROLES.DEVOPS]: [
    PERMISSIONS.DEVOPS_DASHBOARD_READ,
    PERMISSIONS.DEVOPS_PROJECT_READ,
    PERMISSIONS.DEVOPS_DEPLOYMENT_READ,
    PERMISSIONS.DEVOPS_DEPLOYMENT_CREATE,
    PERMISSIONS.DEVOPS_SERVER_READ,
  ],
  [ROLES.REPRESENTATIVE]: [
    PERMISSIONS.REPRESENTATIVE_DASHBOARD_READ,
    PERMISSIONS.REPRESENTATIVE_PROJECT_READ,
    PERMISSIONS.REPRESENTATIVE_TICKET_READ,
    PERMISSIONS.REPRESENTATIVE_TICKET_CREATE,
    PERMISSIONS.REPRESENTATIVE_TICKET_UPDATE,
  ],
  [ROLES.QA]: [
    PERMISSIONS.QA_DASHBOARD_READ,
    PERMISSIONS.QA_PROJECT_READ,
    PERMISSIONS.QA_TEST_CASE_READ,
    PERMISSIONS.QA_TEST_CASE_CREATE,
    PERMISSIONS.QA_TEST_CASE_UPDATE,
    PERMISSIONS.QA_VULNERABILITY_READ,
  ],
  [ROLES.PROJECT_MANAGER_SECURITY]: [
    PERMISSIONS.SPM_DASHBOARD_READ,
    PERMISSIONS.SPM_PROJECT_READ,
    PERMISSIONS.SPM_PROJECT_UPDATE,
    PERMISSIONS.SPM_PROJECT_ASSIGN_USERS,
    PERMISSIONS.SPM_PROJECT_MANAGE_SECURITY,
    PERMISSIONS.SPM_PENTEST_READ,
    PERMISSIONS.SPM_VULNERABILITY_READ,
    PERMISSIONS.SPM_REPORT_EXPORT,
  ],
  [ROLES.PROJECT_MANAGER_QA]: [
    PERMISSIONS.QPM_DASHBOARD_READ,
    PERMISSIONS.QPM_PROJECT_READ,
    PERMISSIONS.QPM_PROJECT_UPDATE,
    PERMISSIONS.QPM_PROJECT_ASSIGN_USERS,
    PERMISSIONS.QPM_PROJECT_MANAGE_QA,
    PERMISSIONS.QPM_QA_READ,
    PERMISSIONS.QPM_TEST_CASE_READ,
    PERMISSIONS.QPM_TEST_CASE_UPDATE,
  ],
};

export function getPermissionsFromRoles(roles: Role[] = []): Permission[] {
  return Array.from(new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role] || [])));
}
