import { ROLES, type Role } from "./roles";
import { PERMISSIONS, type Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PENTESTER]: [
    PERMISSIONS.PENTEST_DASHBOARD_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.VULNERABILITIES_READ,
    PERMISSIONS.VULNERABILITIES_CREATE,
    PERMISSIONS.VULNERABILITIES_UPDATE,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  [ROLES.DEVOPS]: [
    PERMISSIONS.DEVOPS_DASHBOARD_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.DEPLOYMENTS_READ,
    PERMISSIONS.DEPLOYMENTS_CREATE,
    PERMISSIONS.SERVERS_READ,
  ],
  [ROLES.REPRESENTATIVE]: [
    PERMISSIONS.REPRESENTATIVE_DASHBOARD_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_UPDATE,
  ],
  [ROLES.QA]: [
    PERMISSIONS.QA_DASHBOARD_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.QA_TEST_CASES_READ,
    PERMISSIONS.QA_TEST_CASES_CREATE,
    PERMISSIONS.QA_TEST_CASES_UPDATE,
    PERMISSIONS.VULNERABILITIES_READ,
  ],
  [ROLES.PROJECT_MANAGER_SECURITY]: [
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.PROJECTS_ASSIGN_USERS,
    PERMISSIONS.PROJECTS_MANAGE_SECURITY,
    PERMISSIONS.PENTEST_DASHBOARD_READ,
    PERMISSIONS.VULNERABILITIES_READ,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  [ROLES.PROJECT_MANAGER_QA]: [
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.PROJECTS_ASSIGN_USERS,
    PERMISSIONS.PROJECTS_MANAGE_QA,
    PERMISSIONS.QA_DASHBOARD_READ,
    PERMISSIONS.QA_TEST_CASES_READ,
    PERMISSIONS.QA_TEST_CASES_UPDATE,
  ],
};

export function getPermissionsFromRoles(roles: Role[] = []): Permission[] {
  return Array.from(new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role] || [])));
}
